# Site settings
title: Feuerwehr Eisolzried
description: >
  Aktuelle Neuigkeiten, Termine und Wissenswertes der Feuerwehr Eisolzried im BÃ¼rgerhaus Deutenhausen-Eisolzried in der Gemeinde Bergkirchen
baseurl: ""
url: https://feuerwehr-eisolzried.de
repo: https://github.com/midzer/eisolzried
email: info@feuerwehr-eisolzried.de

# SEO/Meta settings
author: midzer
seo:
  name: Feuerwehr Eisolzried
  type: Organisation

# Build settings
markdown: kramdown
permalink: pretty
include: ['_pages']
exclude:
  - vendor
  - config.json
  - Gemfile
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.babel.js
  - yarn.lock
keep_files:
  - charts

# Plugin settings
plugins:
  - i18n
  - jekyll-seo-tag