# Site settings
title: Feuerwehr Eisolzried
email: info@feuerwehr-eisolzried.de
description: "Aktuelle Neuigkeiten, Termine und Wissenswertes der Feuerwehr Eisolzried im BÃ¼rgerhaus Deutenhausen-Eisolzried in der Gemeinde Bergkirchen"
baseurl: ""
url: "https://feuerwehr-eisolzried.de"
github_username: midzer/eisolzried

# Build settings
markdown: kramdown
permalink: pretty
keep_files: [/charts]
exclude: [vendor,config.json,Gemfile,README.md,node_modules,package.json,package-lock.json,gulpfile.babel.js]
